locales:
  en:
    name: Kiowa Keyboards
    description: Mobile OS keyboards for the Kiowa language from the Divvun group at UiT.
  nb:
    name: Kiowa tastatur
    description: Mobiltastatur for Kiowa fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
